/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplicationGuideRouteImport } from './routes/application-guide'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as GamesRouteImport } from './routes/games'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IronOnNamesRouteImport } from './routes/iron-on-names'
import { Route as MakeYourNameRouteImport } from './routes/make-your-name'
import { Route as NamePacksRouteImport } from './routes/name-packs'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as PersonalisedRouteImport } from './routes/personalised'
import { Route as SchoolPacksRouteImport } from './routes/school-packs'
import { Route as SeasonalRouteImport } from './routes/seasonal'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StickOnNamesRouteImport } from './routes/stick-on-names'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationGuideRoute = ApplicationGuideRouteImport.update({
  id: '/application-guide',
  path: '/application-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IronOnNamesRoute = IronOnNamesRouteImport.update({
  id: '/iron-on-names',
  path: '/iron-on-names',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeYourNameRoute = MakeYourNameRouteImport.update({
  id: '/make-your-name',
  path: '/make-your-name',
  getParentRoute: () => rootRouteImport,
} as any)
const NamePacksRoute = NamePacksRouteImport.update({
  id: '/name-packs',
  path: '/name-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalisedRoute = PersonalisedRouteImport.update({
  id: '/personalised',
  path: '/personalised',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolPacksRoute = SchoolPacksRouteImport.update({
  id: '/school-packs',
  path: '/school-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonalRoute = SeasonalRouteImport.update({
  id: '/seasonal',
  path: '/seasonal',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StickOnNamesRoute = StickOnNamesRouteImport.update({
  id: '/stick-on-names',
  path: '/stick-on-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/basket': typeof BasketRoute
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/iron-on-names': typeof IronOnNamesRoute
  '/make-your-name': typeof MakeYourNameRoute
  '/name-packs': typeof NamePacksRoute
  '/parties': typeof PartiesRoute
  '/personalised': typeof PersonalisedRoute
  '/school-packs': typeof SchoolPacksRoute
  '/seasonal': typeof SeasonalRoute
  '/shop': typeof ShopRoute
  '/stick-on-names': typeof StickOnNamesRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/basket': typeof BasketRoute
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/iron-on-names': typeof IronOnNamesRoute
  '/make-your-name': typeof MakeYourNameRoute
  '/name-packs': typeof NamePacksRoute
  '/parties': typeof PartiesRoute
  '/personalised': typeof PersonalisedRoute
  '/school-packs': typeof SchoolPacksRoute
  '/seasonal': typeof SeasonalRoute
  '/shop': typeof ShopRoute
  '/stick-on-names': typeof StickOnNamesRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/basket': typeof BasketRoute
  '/games': typeof GamesRoute
  '/gifts': typeof GiftsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/iron-on-names': typeof IronOnNamesRoute
  '/make-your-name': typeof MakeYourNameRoute
  '/name-packs': typeof NamePacksRoute
  '/parties': typeof PartiesRoute
  '/personalised': typeof PersonalisedRoute
  '/school-packs': typeof SchoolPacksRoute
  '/seasonal': typeof SeasonalRoute
  '/shop': typeof ShopRoute
  '/stick-on-names': typeof StickOnNamesRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/application-guide'
    | '/basket'
    | '/games'
    | '/gifts'
    | '/how-it-works'
    | '/iron-on-names'
    | '/make-your-name'
    | '/name-packs'
    | '/parties'
    | '/personalised'
    | '/school-packs'
    | '/seasonal'
    | '/shop'
    | '/stick-on-names'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/application-guide'
    | '/basket'
    | '/games'
    | '/gifts'
    | '/how-it-works'
    | '/iron-on-names'
    | '/make-your-name'
    | '/name-packs'
    | '/parties'
    | '/personalised'
    | '/school-packs'
    | '/seasonal'
    | '/shop'
    | '/stick-on-names'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/application-guide'
    | '/basket'
    | '/games'
    | '/gifts'
    | '/how-it-works'
    | '/iron-on-names'
    | '/make-your-name'
    | '/name-packs'
    | '/parties'
    | '/personalised'
    | '/school-packs'
    | '/seasonal'
    | '/shop'
    | '/stick-on-names'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationGuideRoute: typeof ApplicationGuideRoute
  BasketRoute: typeof BasketRoute
  GamesRoute: typeof GamesRoute
  GiftsRoute: typeof GiftsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  IronOnNamesRoute: typeof IronOnNamesRoute
  MakeYourNameRoute: typeof MakeYourNameRoute
  NamePacksRoute: typeof NamePacksRoute
  PartiesRoute: typeof PartiesRoute
  PersonalisedRoute: typeof PersonalisedRoute
  SchoolPacksRoute: typeof SchoolPacksRoute
  SeasonalRoute: typeof SeasonalRoute
  ShopRoute: typeof ShopRoute
  StickOnNamesRoute: typeof StickOnNamesRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-guide': {
      id: '/application-guide'
      path: '/application-guide'
      fullPath: '/application-guide'
      preLoaderRoute: typeof ApplicationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iron-on-names': {
      id: '/iron-on-names'
      path: '/iron-on-names'
      fullPath: '/iron-on-names'
      preLoaderRoute: typeof IronOnNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make-your-name': {
      id: '/make-your-name'
      path: '/make-your-name'
      fullPath: '/make-your-name'
      preLoaderRoute: typeof MakeYourNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/name-packs': {
      id: '/name-packs'
      path: '/name-packs'
      fullPath: '/name-packs'
      preLoaderRoute: typeof NamePacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalised': {
      id: '/personalised'
      path: '/personalised'
      fullPath: '/personalised'
      preLoaderRoute: typeof PersonalisedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-packs': {
      id: '/school-packs'
      path: '/school-packs'
      fullPath: '/school-packs'
      preLoaderRoute: typeof SchoolPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasonal': {
      id: '/seasonal'
      path: '/seasonal'
      fullPath: '/seasonal'
      preLoaderRoute: typeof SeasonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stick-on-names': {
      id: '/stick-on-names'
      path: '/stick-on-names'
      fullPath: '/stick-on-names'
      preLoaderRoute: typeof StickOnNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationGuideRoute: ApplicationGuideRoute,
  BasketRoute: BasketRoute,
  GamesRoute: GamesRoute,
  GiftsRoute: GiftsRoute,
  HowItWorksRoute: HowItWorksRoute,
  IronOnNamesRoute: IronOnNamesRoute,
  MakeYourNameRoute: MakeYourNameRoute,
  NamePacksRoute: NamePacksRoute,
  PartiesRoute: PartiesRoute,
  PersonalisedRoute: PersonalisedRoute,
  SchoolPacksRoute: SchoolPacksRoute,
  SeasonalRoute: SeasonalRoute,
  ShopRoute: ShopRoute,
  StickOnNamesRoute: StickOnNamesRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
